#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#include <iostream>
#include <json/json.hpp>

using json = nlohmann::json;

enum CoveredSetExtraction {F1, BACC, AUC};

enum LossFunctionType {MISCLASSIFICATION, LOG_LOSS, SQUARED_ERROR};

// Static configuration object used to modifie the algorithm behaviour
// By design, all running instances of the algorithm within the same process must share the same configuration
//
// THREAD-SAFETY GUARANTEE:
// Configuration MUST be fully initialized via configure() before worker threads are created.
// After threads start, all Configuration members are READ-ONLY. Modifying Configuration after
// thread creation causes undefined behavior. The Configuration::worker_limit value is the last
// configuration value that can change, and it must be finalized before gosdt.cpp starts threads.
class Configuration {
public:
    static void configure(std::istream & configuration);
    static void configure(json source);
    static std::string to_string(unsigned int spacing = 0);

    static float uncertainty_tolerance; // The maximum allowed global optimality before the optimization can terminate
    static float regularization; // The penalty incurred for each leaf inthe model
    static float upperbound; // Upperbound on the root problem for pruning problems using a greedy model

    static unsigned int time_limit; // The maximum allowed runtime (seconds). 0 means unlimited.
    static unsigned int worker_limit; // The maximum allowed worker threads. 0 means match number of available cores
    static unsigned int stack_limit; // The maximum amount of stack space (bytes) allowed to use as buffers
    static unsigned int precision_limit; // The maximum number of significant figures considered for each ordinal feature
    static unsigned int model_limit; // The maximum number of models extracted

    static bool verbose; // Flag for printing status to standard output
    static bool diagnostics; // Flag for printing diagnosis to standard output if a bug is detected

    static unsigned char depth_budget; // The maximum tree depth for solutions, counting a tree with just the root node as depth 1. 0 means unlimited.

    static unsigned int minimum_captured_points; // The mimimum captured points for any leaf

    // Subgroup-aware minimum leaf size. Where minimum_captured_points floors a leaf's
    // TOTAL size, these floor the size of each arm of a binary subgroup indicator
    // within the leaf. Motivation: a leaf with m_n total units that happen to be all
    // treated yields a fitted propensity of exactly 1, hence an infinite ATT weight
    // p/(1-p). See quality_reports/specs/2026-08-20_leaf-size-subgroup-enforcement.md
    // in the global-scholars project.
    //
    // subgroup_target_index indexes the encoder's binary TARGET (label) indicator columns,
    // i.e. Dataset::targets, so it lies in [0, Dataset::depth()). For a 0/1 label the
    // encoder emits targets[0] = 1{y == "0"} and targets[1] = 1{y == "1"} (values are
    // ordered as strings by Encoder::build()). Selecting the 1{y == 1} indicator makes
    // subgroup_min_count_0 a floor on control rows, which is what the propensity tree
    // needs. -1 (the default) disables the check entirely, so the feature is opt-in and
    // fully backward compatible.
    //
    // Counts are RAW physical row counts (Bitmask::count() over Dataset rows), the
    // identical convention used by the minimum_captured_points check in
    // Task::create_children(). The dataset is not deduplicated or weighted, so a raw
    // row count is also the raw sample count.
    //
    // Comparison is strict `<` (a true minimum: a leaf with exactly m0/m1 rows in
    // that arm is feasible), UNLIKE minimum_captured_points, which uses `<=` and so
    // rejects a leaf with exactly minimum_captured_points rows. Do not assume the two
    // fields share an operator just because they share a name pattern.
    static int subgroup_target_index;
    static unsigned int subgroup_min_count_0; // m0: minimum rows per leaf with the indicator == 0
    static unsigned int subgroup_min_count_1; // m1: minimum rows per leaf with the indicator == 1

    static std::vector<int> memory_checkpoints; // Memory at which to dump trie generated by current adjency graph

    static bool output_accuracy_model_set;
    static std::vector<CoveredSetExtraction> output_covered_sets; 
    static std::vector<double> covered_sets_thresholds;
    static std::string covered_set_type_to_string(CoveredSetExtraction type) {
        switch (type) {
            case F1:
                return "f1";
            case BACC:
                return "bacc";
            case AUC:
                return "auc";
            default:
                throw std::invalid_argument("Unknown type");
        }
    };
    static double computeScore(CoveredSetExtraction type, unsigned int P, unsigned int N, double TP, double TN) {
        // Validate inputs before division
        if (P == 0 || N == 0) {
            throw std::runtime_error("Cannot compute score with P=0 or N=0");
        }

        switch (type) {
            case F1: {
                double denom = TP + 0.5 * (P - TP + N - TN);
                if (denom == 0.0) {
                    throw std::runtime_error("F1 score denominator is zero");
                }
                return TP / denom;
            }
            case BACC:
                return (TP / P + TN / N) / 2.0;
            case AUC:
                return (TN * TP + 0.5 * (TP * (N - TN) + TN * (P - TP))) / (N * P);
            default:
                throw std::invalid_argument("Unknown score type");
        }
    };

    static bool balance; // Flag for adjusting the importance of each row to equalize the total importance of each class (overrides weight)
    static bool look_ahead; // Flag for enabling the one-step look-ahead bound implemented via scopes
    static bool similar_support; // Flag for enabling the similar support bound imeplemented via the distance index
    static bool cancellation; // Flag for enabling upward propagation of cancelled subproblems
    static bool continuous_feature_exchange; // Flag for enabling the pruning of neighbouring thresholds using subset comparison
    static bool feature_exchange; // Flag for enabling the pruning of pairs of features using subset comparison
    static bool feature_transform; // Flag for enabling the equivalence discovery through simple feature transformations
    static bool rule_list; // Flag for enabling rule-list constraints on models
    static bool non_binary; // Flag for enabling non-binary encoding

    static std::string costs; // Path to file containing cost matrix
    static std::string model; // Path to file used to store the extracted models
    static std::string rashomon_model; // Path to directory used to store the Rashomon set
    static std::string rashomon_model_set_suffix; // Path to directory used to store the Rashomon model set
    static std::string rashomon_trie; // Path to directory used to store the Rashomon trie
    static std::string timing; // Path to file used to store training time
    static std::string trace; // Path to directory used to store traces
    static std::string tree; // Path to directory used to store tree-traces
    static std::string profile; // Path to file used to log runtime statistics
    static std::string datatset_encoding; // Path to file used store dataset encoding

    static bool rashomon; // Flag for extracting Rashomon set
    
    // The following three are mutually exclusive. Please only set one to be true
    static float rashomon_bound; // If the rashomon bound is known, setting this would skip finding the optimal tree
    static float rashomon_bound_multiplier; // Setting the Rashomon bound to be (Optimal Objective Value) * (1 + rashomon_bound_multiplier)
    static float rashomon_bound_adder; // Setting the Rashomon bound to be (Optimal Objective Value) + rashomon_bound_adder

    static bool rashomon_ignore_trivial_extensions;

    static LossFunctionType loss_function; // Loss function to use for optimization

    static bool cart_lookahead;              // Enable CART lookahead bounds for faster optimization
    static unsigned int cart_lookahead_depth; // Depth for CART lookahead (0=disabled, 1-3 typical)

    static bool k_cluster;                   // Enable k-Means lower bounds for regression (OSRT Theorems 3.4-3.5)

    static float huber_delta;                // Delta parameter for Huber loss (transition point between quadratic and linear)
    static float quantile_tau;               // Tau parameter for quantile loss (quantile level, e.g., 0.5 for median)

};

#endif