// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// treefarms_configure_cpp
void treefarms_configure_cpp(std::string configuration);
RcppExport SEXP _treefarms_treefarms_configure_cpp(SEXP configurationSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type configuration(configurationSEXP);
    treefarms_configure_cpp(configuration);
    return R_NilValue;
END_RCPP
}
// treefarms_fit_cpp
std::string treefarms_fit_cpp(std::string data_csv);
RcppExport SEXP _treefarms_treefarms_fit_cpp(SEXP data_csvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type data_csv(data_csvSEXP);
    rcpp_result_gen = Rcpp::wrap(treefarms_fit_cpp(data_csv));
    return rcpp_result_gen;
END_RCPP
}
// treefarms_time_cpp
double treefarms_time_cpp();
RcppExport SEXP _treefarms_treefarms_time_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(treefarms_time_cpp());
    return rcpp_result_gen;
END_RCPP
}
// treefarms_iterations_cpp
int treefarms_iterations_cpp();
RcppExport SEXP _treefarms_treefarms_iterations_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(treefarms_iterations_cpp());
    return rcpp_result_gen;
END_RCPP
}
// treefarms_size_cpp
int treefarms_size_cpp();
RcppExport SEXP _treefarms_treefarms_size_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(treefarms_size_cpp());
    return rcpp_result_gen;
END_RCPP
}
// treefarms_status_cpp
int treefarms_status_cpp();
RcppExport SEXP _treefarms_treefarms_status_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(treefarms_status_cpp());
    return rcpp_result_gen;
END_RCPP
}
// treefarms_fit_with_config_cpp
std::string treefarms_fit_with_config_cpp(std::string data_csv, std::string configuration);
RcppExport SEXP _treefarms_treefarms_fit_with_config_cpp(SEXP data_csvSEXP, SEXP configurationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type data_csv(data_csvSEXP);
    Rcpp::traits::input_parameter< std::string >::type configuration(configurationSEXP);
    rcpp_result_gen = Rcpp::wrap(treefarms_fit_with_config_cpp(data_csv, configuration));
    return rcpp_result_gen;
END_RCPP
}
// treefarms_fit_and_stats_cpp
Rcpp::List treefarms_fit_and_stats_cpp(std::string data_csv, std::string configuration);
RcppExport SEXP _treefarms_treefarms_fit_and_stats_cpp(SEXP data_csvSEXP, SEXP configurationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type data_csv(data_csvSEXP);
    Rcpp::traits::input_parameter< std::string >::type configuration(configurationSEXP);
    rcpp_result_gen = Rcpp::wrap(treefarms_fit_and_stats_cpp(data_csv, configuration));
    return rcpp_result_gen;
END_RCPP
}
// cleanup_static_state
void cleanup_static_state();
RcppExport SEXP _treefarms_cleanup_static_state() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cleanup_static_state();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treefarms_treefarms_configure_cpp", (DL_FUNC) &_treefarms_treefarms_configure_cpp, 1},
    {"_treefarms_treefarms_fit_cpp", (DL_FUNC) &_treefarms_treefarms_fit_cpp, 1},
    {"_treefarms_treefarms_time_cpp", (DL_FUNC) &_treefarms_treefarms_time_cpp, 0},
    {"_treefarms_treefarms_iterations_cpp", (DL_FUNC) &_treefarms_treefarms_iterations_cpp, 0},
    {"_treefarms_treefarms_size_cpp", (DL_FUNC) &_treefarms_treefarms_size_cpp, 0},
    {"_treefarms_treefarms_status_cpp", (DL_FUNC) &_treefarms_treefarms_status_cpp, 0},
    {"_treefarms_treefarms_fit_with_config_cpp", (DL_FUNC) &_treefarms_treefarms_fit_with_config_cpp, 2},
    {"_treefarms_treefarms_fit_and_stats_cpp", (DL_FUNC) &_treefarms_treefarms_fit_and_stats_cpp, 2},
    {"_treefarms_cleanup_static_state", (DL_FUNC) &_treefarms_cleanup_static_state, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_treefarms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
